// tests/chat.test.js — assistant.db, the chat record, now cut into sessions.
//
// Contract under test: a `messages` table (id, session_id, role, content,
// created_at, steps, usage, cost, deleted_at) and a `sessions` table
// (id, title, created_at, updated_at, deleted_at) in databases/assistant.db —
// ASSISTANT_DB overrides, exactly as BOARD_DB does for the board — exposed as:
//
//   GET  /api/chat/messages       -> { messages: [{id, sessionId, role, content,
//                                     createdAt}] }
//        live rows only, ordered by createdAt then id, so an imported older
//        transcript reads in chronological order. Rows belonging to a
//        soft-deleted session are NOT live.
//   POST /api/chat/messages       <- { messages: [{role, content, createdAt?,
//                                     steps?, usage?, cost?}], sessionId? }
//        role is user|assistant, content a non-empty string; createdAt is
//        optional (imports keep their own timestamps, live turns are stamped
//        by the server). An invalid row refuses the whole batch — the record
//        never takes half an import. sessionId is optional: a batch without
//        one lands in the reserved 'adhoc' session, so a curl or an eval is
//        recorded and is visibly separate from a real conversation.
//   GET    /api/chat/sessions     -> { sessions: [{id, title, createdAt,
//                                     updatedAt, messageCount}] }
//        live only, newest updatedAt first — the history panel's list.
//   GET    /api/chat/sessions/:id -> { session, messages: [...] } with each
//        turn's steps/usage/cost, which is what makes reopening a historic
//        chat show its tool evidence and its price.
//   PATCH  /api/chat/sessions/:id <- { title }   rename; an empty title refuses.
//   DELETE /api/chat/sessions/:id -> soft delete: sessions.deleted_at is set,
//        every message row survives, and nothing live returns them.
//
// A session's title is DERIVED from its first user message (first line, 60
// chars) at creation, never generated by a model: it costs nothing, it cannot
// arrive untitled, and it is renameable.
//
// There is still deliberately NO hard delete for chat. DELETE is soft, and it
// is the only destructive route the record has ever gained — the durability
// promise is that a message row is never removed by any API call.

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { startServer } from './helpers/server-harness.mjs';

// Sessions are minted by the browser (crypto.randomUUID), so a test simply
// names its own.
const S1 = 'session-berlin';
const S2 = 'session-taxes';

async function post(base, body) {
  return fetch(base + '/api/chat/messages', {
    method: 'POST', headers: { 'content-type': 'application/json' },
    body: JSON.stringify(body),
  });
}

const list = async (base) =>
  (await (await fetch(base + '/api/chat/messages')).json()).messages;

const sessions = async (base) =>
  (await (await fetch(base + '/api/chat/sessions')).json()).sessions;

const transcript = async (base, id) =>
  (await fetch(base + '/api/chat/sessions/' + id)).json();

const byId = (rows, id) => rows.find((r) => r.id === id);

// This is an integration test.
test('POST appends to the record; GET returns it in chronological order', async () => {
  const s = await startServer();
  try {
    // A live turn: both sides recorded, server stamps createdAt.
    const res = await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: 'remember the wifi password is hunter2' },
      { role: 'assistant', content: 'Noted — the wifi password is hunter2.' },
    ] });
    assert.equal(res.status, 200);
    const { messages: saved } = await res.json();
    assert.equal(saved.length, 2);
    assert.ok(saved[0].id && saved[1].id && saved[0].id !== saved[1].id);
    assert.ok(saved[0].createdAt > 0, 'the server stamps createdAt when absent');
    assert.equal(saved[0].sessionId, S1,
      'the inserted rows name their session — the brain indexes what comes back');

    // An import: an older message keeps its own timestamp and sorts first.
    const old = await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: 'from the old transcript', createdAt: 1000 },
    ] });
    assert.equal(old.status, 200);
    const all = await list(s.base);
    assert.deepEqual(all.map((m) => m.content), [
      'from the old transcript',
      'remember the wifi password is hunter2',
      'Noted — the wifi password is hunter2.',
    ]);
    assert.equal(all[0].createdAt, 1000, 'an imported createdAt is preserved');
  } finally { await s.stop(); }
});

// This is an integration test.
test('the record is separate from the board and survives a restart', async () => {
  // Fixed paths so a second server can reopen the same databases.
  const dir = mkdtempSync(join(tmpdir(), 'chat-'));
  const env = { BOARD_DB: join(dir, 'board.db'), ASSISTANT_DB: join(dir, 'assistant.db') };

  const s1 = await startServer({ env });
  try {
    await post(s1.base, { sessionId: S1, messages: [
      { role: 'user', content: 'does this survive?' },
      { role: 'assistant', content: 'It must.' },
    ] });
    assert.ok(existsSync(env.ASSISTANT_DB), 'chat lives in its own file');

    // The whole-board save — the API that soft-deletes omitted cards — must
    // have no reach into the chat record. This is why there are two files.
    const put = await fetch(s1.base + '/api/state', {
      method: 'PUT', headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ version: 1, cards: [] }),
    });
    assert.equal(put.status, 200);
    assert.equal((await list(s1.base)).length, 2, 'a board save cannot touch chat');
  } finally { await s1.stop(); }

  const s2 = await startServer({ env });
  try {
    const all = await list(s2.base);
    assert.deepEqual(all.map((m) => m.content), ['does this survive?', 'It must.']);
    // The session outlives the process too, or reopening a historic chat after
    // a restart would find its messages and no chat to put them in.
    const [only] = await sessions(s2.base);
    assert.equal(only.id, S1);
    assert.equal(only.messageCount, 2);
  } finally { await s2.stop(); }
});

// This is an integration test.
test('an invalid message refuses the whole batch and inserts nothing', async () => {
  const s = await startServer();
  try {
    for (const bad of [
      { sessionId: S1, messages: [{ role: 'wizard', content: 'no such role' }] },
      { sessionId: S1, messages: [{ role: 'user', content: '' }] },
      { sessionId: S1, messages: [{ role: 'user', content: 'good' },
                                  { role: 'user', content: '' }] },
      { sessionId: S1, messages: 'not-an-array' },
      // A session id has to be a string if it is given at all: an object here
      // would otherwise be stringified into a session nobody can name again.
      { sessionId: { id: S1 }, messages: [{ role: 'user', content: 'hi' }] },
      {},
    ]) {
      const res = await post(s.base, bad);
      assert.equal(res.status, 400, `must refuse: ${JSON.stringify(bad)}`);
    }
    assert.deepEqual(await list(s.base), [],
      'a refused batch inserts nothing — not even its valid rows');
    assert.deepEqual(await sessions(s.base), [],
      'and a refused batch does not leave an empty session behind');
  } finally { await s.stop(); }
});

// This is an integration test.
test('a session is titled from its first message, counted, and ordered by last activity', async () => {
  const s = await startServer();
  try {
    // The title is the first line, capped at 60 chars. Both halves matter: a
    // pasted paragraph must not become the label of the chat, and a title that
    // ran to the second line would break the row layout of the history panel.
    const long = 'How should I plan the Berlin trip in October with the visa deadline in mind?'
      + '\nsecond line that must never reach the title';
    await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: long, createdAt: 1_000 },
      { role: 'assistant', content: 'Here is a plan.', createdAt: 1_100 },
    ] });
    await post(s.base, { sessionId: S2, messages: [
      { role: 'user', content: 'file the tax return', createdAt: 2_000 },
    ] });

    const listed = await sessions(s.base);
    assert.deepEqual(listed.map((x) => x.id), [S2, S1],
      'newest activity first — the history panel reads top-down');
    const berlin = byId(listed, S1);
    assert.equal(berlin.title, long.split('\n')[0].slice(0, 60),
      'first line, 60 chars, no ellipsis invented by the server');
    assert.equal(berlin.title.length, 60, 'the cap is applied, not merely available');
    assert.ok(!berlin.title.includes('\n'), 'a title is one line');
    assert.equal(berlin.messageCount, 2, 'counted in SQL, not by loading the transcript');
    assert.equal(berlin.createdAt, 1_000);
    assert.equal(berlin.updatedAt, 1_100, 'updatedAt follows the newest message');

    // A later turn in the older chat moves it back to the top: that is what
    // makes the list read as "what I am working on", not "what I started".
    await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: 'and the trains?', createdAt: 3_000 },
    ] });
    assert.deepEqual((await sessions(s.base)).map((x) => x.id), [S1, S2]);
    assert.equal(byId(await sessions(s.base), S1).title, berlin.title,
      'a second turn must not retitle the chat from a later message');
  } finally { await s.stop(); }
});

// This is an integration test.
test('a session transcript carries each turn steps, usage and cost', async () => {
  const s = await startServer();
  try {
    const steps = [{ tool: 'web_search', arguments: { query: 'berlin visa' },
                     result: [{ title: 'Visa rules', url: 'https://example.com/v' }] }];
    await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: 'berlin visa rules?' },
      { role: 'assistant', content: 'Here they are.', steps,
        usage: { input_tokens: 900, output_tokens: 120, total_tokens: 1020 },
        cost: 0.00042 },
      // An unpriced turn: the model reported nothing, so there is no bill. It
      // must come back NULL, never 0 — pricing.py refuses to fabricate a zero
      // and a stored 0 would be a measurement nobody made.
      { role: 'assistant', content: 'And a free one.' },
    ] });

    const { session, messages } = await transcript(s.base, S1);
    assert.equal(session.id, S1);
    assert.equal(messages.length, 3);
    assert.deepEqual(messages[1].steps, steps,
      'the tool evidence survives, so a reopened chat is not just its prose');
    assert.equal(messages[1].usage.total_tokens, 1020);
    assert.equal(messages[1].cost, 0.00042);
    assert.deepEqual(messages[0].steps, [], 'a user row has no steps, not null');
    assert.equal(messages[2].usage, null, 'unreported usage is null, not {}');
    assert.equal(messages[2].cost, null, 'an unpriced turn is null, never 0');

    assert.equal((await fetch(s.base + '/api/chat/sessions/no-such')).status, 404);
  } finally { await s.stop(); }
});

// This is an integration test.
test('renaming refuses an empty title; deleting is soft and hides the chat', async () => {
  const s = await startServer();
  try {
    await post(s.base, { sessionId: S1, messages: [
      { role: 'user', content: 'the original subject' }] });
    await post(s.base, { sessionId: S2, messages: [
      { role: 'user', content: 'a chat that stays' }] });

    const rename = (id, title) => fetch(s.base + '/api/chat/sessions/' + id, {
      method: 'PATCH', headers: { 'content-type': 'application/json' },
      body: JSON.stringify({ title }),
    });
    assert.equal((await rename(S1, 'Berlin trip')).status, 200);
    assert.equal(byId(await sessions(s.base), S1).title, 'Berlin trip');
    for (const empty of ['', '   ', '\n']) {
      assert.equal((await rename(S1, empty)).status, 400,
        'a blank title would leave an unnameable row in the history panel');
    }
    assert.equal(byId(await sessions(s.base), S1).title, 'Berlin trip',
      'a refused rename leaves the old title intact');

    const del = await fetch(s.base + '/api/chat/sessions/' + S1, { method: 'DELETE' });
    assert.equal(del.status, 200);
    assert.deepEqual((await sessions(s.base)).map((x) => x.id), [S2],
      'a deleted chat leaves the history panel');
    assert.deepEqual((await list(s.base)).map((m) => m.content), ['a chat that stays'],
      'and its messages leave the live record, so recall stops answering from it');

    // The durability promise: nothing was destroyed, only hidden. Read the file
    // directly — no API exposes an archived chat, which is the point.
    const db = new DatabaseSync(s.assistantDbPath, { readOnly: true });
    try {
      const rows = db.prepare('SELECT content FROM messages WHERE session_id = ?').all(S1);
      assert.deepEqual(rows.map((r) => r.content), ['the original subject'],
        'DELETE is soft: the message rows are still in assistant.db');
      const gone = db.prepare('SELECT deleted_at FROM sessions WHERE id = ?').get(S1);
      assert.ok(gone.deleted_at > 0, 'the session is stamped, not removed');
    } finally { db.close(); }
  } finally { await s.stop(); }
});

// This is an integration test.
test('a record written before sessions is adopted into Earlier conversations', async () => {
  // The pre-session schema, built by hand: this is the shape every existing
  // board has on disk today, and the migration has exactly one chance to get
  // it right. Without adoption the user's whole history would be invisible —
  // present in the file, absent from every list.
  const dir = mkdtempSync(join(tmpdir(), 'chat-migrate-'));
  const env = { BOARD_DB: join(dir, 'board.db'), ASSISTANT_DB: join(dir, 'assistant.db') };
  const old = new DatabaseSync(env.ASSISTANT_DB);
  old.exec(`
    CREATE TABLE messages (
      id         INTEGER PRIMARY KEY AUTOINCREMENT,
      role       TEXT    NOT NULL,
      content    TEXT    NOT NULL,
      created_at INTEGER NOT NULL,
      deleted_at INTEGER
    );
  `);
  const insert = old.prepare('INSERT INTO messages (role, content, created_at) VALUES (?, ?, ?)');
  insert.run('user', 'what did we decide about the flat?', 1_000);
  insert.run('assistant', 'You decided to stay another year.', 1_100);
  old.close();

  const s = await startServer({ env });
  try {
    const listed = await sessions(s.base);
    assert.equal(listed.length, 1, 'one session for the whole pre-session record');
    assert.equal(listed[0].title, 'Earlier conversations');
    assert.equal(listed[0].messageCount, 2);
    assert.equal(listed[0].updatedAt, 1_100,
      'the adopted chat is dated by its own messages, not by the migration');

    const rows = await list(s.base);
    assert.ok(rows.every((m) => m.sessionId === listed[0].id),
      'session_id is never empty after boot — no read path needs a NULL branch');
    const { messages } = await transcript(s.base, listed[0].id);
    assert.deepEqual(messages.map((m) => m.content),
      ['what did we decide about the flat?', 'You decided to stay another year.']);
  } finally { await s.stop(); }
});

// This is an integration test.
test('a batch with no sessionId lands in the reserved Unsessioned chat', async () => {
  const s = await startServer();
  try {
    // What a curl, an eval, or a brain that was not told a session produces.
    // It must be recorded — losing it would be the bug this whole record
    // exists to prevent — and it must not be mixed into a real conversation.
    const res = await post(s.base, { messages: [
      { role: 'user', content: 'recorded by a caller that named no chat' }] });
    assert.equal(res.status, 200);
    const [only] = await sessions(s.base);
    assert.equal(only.id, 'adhoc');
    assert.equal(only.title, 'Unsessioned (API)');
    assert.equal(only.messageCount, 1);

    // Every later unsessioned batch joins the same one rather than breeding a
    // session per call, which would bury real chats under noise.
    await post(s.base, { messages: [{ role: 'user', content: 'and another' }] });
    assert.equal((await sessions(s.base)).length, 1);
    assert.equal((await sessions(s.base))[0].messageCount, 2);
  } finally { await s.stop(); }
});
