-- scripts/postgres/001-schema.sql — the board and the chat record, in Postgres.
--
-- A faithful mirror of the two SQLite databases server.js creates: same table
-- names, same column names, same defaults. tests/postgres.test.js derives the
-- expected tables and columns from server.js itself and fails the moment this
-- file falls behind — a mirror allowed to drift is a migration that loses a
-- column on the day it runs.
--
-- Applied by hand (`npm run postgres:schema`), not by the server's run-once
-- init directory: the server belongs to no application. So every statement here
-- is repeatable, and running it twice is a no-op rather than a half-applied
-- schema.
--
-- Type mapping, and the three places it is not one-to-one:
--
--   TEXT     -> TEXT              unchanged.
--   INTEGER  -> BIGINT            every INTEGER here is either a millisecond
--                                 epoch stamp (created_at, updated_at,
--                                 deleted_at) or a small counter. Date.now()
--                                 passed 2^31 milliseconds in 2038 terms long
--                                 ago; INTEGER is 4 bytes in Postgres and would
--                                 overflow, unlike SQLite's, which widens on
--                                 its own. Counters take BIGINT too rather than
--                                 mixing widths for no reason.
--   REAL     -> DOUBLE PRECISION  messages.cost. NUMERIC would be the careful
--                                 choice for money, but this column holds an
--                                 estimate the SQLite side already stores as a
--                                 float, and changing its precision here would
--                                 make the two records disagree about the same
--                                 turn's cost.
--   INTEGER PRIMARY KEY AUTOINCREMENT
--            -> BIGINT GENERATED BY DEFAULT AS IDENTITY
--                                 messages.id. BY DEFAULT, not ALWAYS: a
--                                 migration has to be able to write the ids the
--                                 SQLite rows already carry, and ALWAYS would
--                                 refuse them.
--
-- Two schemas, not one flat namespace: board.db and assistant.db are separate
-- files, which is exactly why sessions.board_id carries no foreign key —
-- SQLite cannot reference across one. Postgres could express that constraint
-- now, and deliberately does not: the separation is a design decision about
-- what the whole-board PUT may sit next to, not a limitation being worked
-- around. Keeping it as a schema boundary keeps the decision visible.

CREATE SCHEMA IF NOT EXISTS board;
CREATE SCHEMA IF NOT EXISTS assistant;


-- ---------------------------------------------------------------------------
-- board.db
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS board.boards (
  id         TEXT PRIMARY KEY,
  name       TEXT   NOT NULL,
  position   BIGINT NOT NULL DEFAULT 0,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  deleted_at BIGINT
);

-- A card names its board. `pending` is the agent's confirmation gate: a
-- proposal is stored pending = 1 and is invisible to the board until the user
-- accepts it. `num` is the permanent ledger number and stays 0 while pending,
-- so a rejected proposal never burns one.
CREATE TABLE IF NOT EXISTS board.cards (
  id            TEXT PRIMARY KEY,
  board_id      TEXT   NOT NULL DEFAULT 'main' REFERENCES board.boards(id),
  column_id     TEXT   NOT NULL,
  title         TEXT   NOT NULL,
  notes         TEXT   NOT NULL DEFAULT '',
  priority      TEXT   NOT NULL DEFAULT 'medium',
  type          TEXT   NOT NULL DEFAULT 'question',
  category      TEXT   NOT NULL DEFAULT '',
  importance    TEXT   NOT NULL DEFAULT '',
  urgency       TEXT   NOT NULL DEFAULT '',
  num           BIGINT NOT NULL DEFAULT 0,
  tags          TEXT   NOT NULL DEFAULT '[]',
  created_at    BIGINT NOT NULL,
  updated_at    BIGINT NOT NULL,
  position      BIGINT NOT NULL DEFAULT 0,
  deleted_at    BIGINT,
  effort        TEXT   NOT NULL DEFAULT 'medium',
  control       TEXT   NOT NULL DEFAULT 'influence',
  effort_src    TEXT   NOT NULL DEFAULT 'default',
  control_src   TEXT   NOT NULL DEFAULT 'default',
  deadline      TEXT   NOT NULL DEFAULT '',
  pending       BIGINT NOT NULL DEFAULT 0,
  habit_freq    TEXT   NOT NULL DEFAULT '',
  habit_count   BIGINT NOT NULL DEFAULT 1,
  habit_times   TEXT   NOT NULL DEFAULT '[]',
  habit_history TEXT   NOT NULL DEFAULT '{}',
  plan          TEXT   NOT NULL DEFAULT '',
  plan_src      TEXT   NOT NULL DEFAULT 'auto'
);

-- The agent's suggested edits. Its own table, never `cards`: the user opens
-- one in the ordinary card dialog, may change it, and applies it by saving.
CREATE TABLE IF NOT EXISTS board.card_edits (
  id         TEXT PRIMARY KEY,
  card_id    TEXT   NOT NULL,
  fields     TEXT   NOT NULL,
  created_at BIGINT NOT NULL
);

-- Per board since 2026-08-20, which is what the composite key records. A
-- shared registry was rewritten by whichever board's stale cached copy pushed
-- last, so categories leaked between boards and deleted ones came back.
CREATE TABLE IF NOT EXISTS board.categories (
  board_id TEXT   NOT NULL DEFAULT 'main' REFERENCES board.boards(id),
  id       TEXT   NOT NULL,
  label    TEXT   NOT NULL,
  h        BIGINT NOT NULL,
  position BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (board_id, id)
);


-- ---------------------------------------------------------------------------
-- assistant.db
-- ---------------------------------------------------------------------------

-- board_id carries no foreign key on purpose — see the header.
CREATE TABLE IF NOT EXISTS assistant.sessions (
  id         TEXT PRIMARY KEY,
  board_id   TEXT   NOT NULL DEFAULT 'main',
  title      TEXT   NOT NULL,
  created_at BIGINT NOT NULL,
  updated_at BIGINT NOT NULL,
  deleted_at BIGINT
);

-- A message belongs to a session, and the session knows its board, so there is
-- no board_id here. session_id defaults to '' rather than NULL because the
-- server has to tell "no session named" apart from a session called nothing:
-- a batch with no session lands in the reserved `adhoc` chat.
CREATE TABLE IF NOT EXISTS assistant.messages (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role       TEXT   NOT NULL,
  content    TEXT   NOT NULL,
  created_at BIGINT NOT NULL,
  deleted_at BIGINT,
  session_id TEXT   NOT NULL DEFAULT '',
  steps      TEXT   NOT NULL DEFAULT '[]',
  usage      TEXT,
  cost       DOUBLE PRECISION
);
